# Generated by Django 2.1 on 2018-08-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180831_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.IntegerField(default=0),
        ),
    ]
